/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118443-gf00a08c0ce-20250207"
#endif /* AVUTIL_FFVERSION_H */
